name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t lernkarten .

      - name: Run tests in container
        run: docker run --rm lernkarten pytest -v --cov=db_library --cov-branch